### ISSUE TITLE
Minutes page needs improvements

### ISSUE THREAD

**Issue by sersorrel** [HackSoc/hacksoc.org#112]
as discussed on slack:

- minutes should be listed in reverse-chronological order
- we need to link to https://github.com/hacksoc/constitution from somewhere on the page

**Comment by adambirtles** [comment]
Other ideas:

- We should probably have headings for each of the committee years
- Fix Android trying to download all the PDFs on page load. Posible solutions include:
    - Not putting the widget into the page until expanded
    - Just don't embed them

Do we need to link to the constitution on the minutes page? Might it be better on the about page?

**Comment by LukeMoll** [comment]
Potentially minutes could be organised into subfolders by committee, so it's easy to see "minutes from the current committee" and "minutes from past committees"

**Comment by LukeMoll** [comment]
All of these issues are resolved by #168.
