### ISSUE TITLE
Windows CI giving a permissions error

### ISSUE THREAD

**Issue by AaronC81** [HackSoc/hacksoc.org#184]
The GH Actions CI on Windows appears to have started failing with a wacky permissions error (see #183):

```
Requirement already satisfied: pip in c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages (21.2.4)
Collecting pip
  Downloading pip-21.3-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pip-uninstall-_kpvves2\\pip.exe'
Consider using the `--user` option or check the permissions.
```

Linux and macOS CI are still working fine.

**Comment by sersorrel** [comment]
"so that contributors don't have to install an entire OS to render their new news article" is i think the intent

**Comment by LordAro** [comment]
Is GH's own markdown previews not good enough? Markdown is supposed to be readable unrendered, after all

e.g. https://github.com/HackSoc/hacksoc.org/blob/02aa6d7f9b6c4236f2bae26ca7d2ce05dc4f167c/templates/content/news/2021-10-19-egm.md

vs

https://www.hacksoc.org/news/2021-10-19-egm.html

**Comment by sersorrel** [comment]
markdown is not entirely standardised, there are undoubtedly differences between github's rendering and the rendering on the website

plus it's nice to support contributions larger than a single article (e.g. improvements to the build system)
