### ISSUE TITLE
Insufficient resolution of front page logo

### ISSUE THREAD

**Issue by icydoge** [HackSoc/hacksoc.org#55]
As shown in this photo:

![Blurry](https://i.imgur.com/aNHk8hX.png)

Due to the limited resolution of the front page [logo](https://www.hacksoc.org/logo2017.png), it looks blurry on high DPI devices such as rMBPs and mobile devices. 

Recommended fix: find the source image and re-export a PNG with double the resolution.

**Comment by LordAro** [comment]
Or y'know, a svg that actually works

**Comment by danieljabailey** [comment]
I think @LordAro is right, this should be an SVG.
Last time I tried I found that the font was the tricky part, I'll see if I can get the font working.
