### ISSUE TITLE
Update minutes page to include pdf.js

### ISSUE THREAD

**Issue by Cascades** [HackSoc/hacksoc.org#61]
I might do this or someone else can.

This is a follow on from #59 which is now closed. Just to test out how embedding pdfs in the page would look.

For more direct reference, looking for something similar to the below mockup!

![Image of EndProduct](https://i.imgur.com/U18thw2.png)

**Comment by LukeMoll** [comment]
I whipped up a quick test of this, couple of differences in my version:

1. Used `+` and `-` in mine, getting triangular arrows that looked consistent was a pain (but can be done if we've got some SVG images of the arrows we want)
2. Didn't use PDF.js, just used `<iframe>` to the PDF url, and Chrome and Firefox just use their inbuilt PDF viewers to render that inline (in the case of Firefox it _is_ PDF.js).

Here's how it looks in Chrome:
![Chrome](https://user-images.githubusercontent.com/7659219/44356715-0af3a200-a4a8-11e8-852b-443153f73120.png)

And in Firefox:
![Firefox](https://user-images.githubusercontent.com/7659219/44356765-34143280-a4a8-11e8-9c67-eea6d64cb037.png)

You can try it out by cloning, running `git checkout pdf-embed`, and then `npm start` as usual - you'll need your own PDF files as there are none on the repo.
