### ISSUE TITLE
Minor content issues in site which could be fixed as part of site revamp

### ISSUE THREAD

**Issue by JMAlego** [HackSoc/hacksoc.org#66]
There are several minor content issues (grammar, style, typos, etc.) on the website, or introduced by the revamp, which should be corrected as part of the website revamp (for the first stage of this, see PR #65). Some of the issues are up for debate as to whether the suggested changes are needed (mainly issues labeled style).

(_Warning: the below list is not sorted by type of issue, this may annoy some people._)

- [x] Style: In general newer content has paragraphs on all one line, whereas older content has paragraphs broken onto multiple lines. We should pick one style and stick to it. A perfect example of this can be seen in the paragraphs below. https://github.com/HackSoc/hacksoc.org/blob/1bbef358249b4fb6821a233a2fcb934c0efef04e/regular/irc.html#L16-L20
- [x] Typo: On the about page the below line should read "Look out for our posters in the [Computer Science](https://tvtropes.org/pmwiki/pmwiki.php/Main/MeaningfulEcho) department." https://github.com/HackSoc/hacksoc.org/blob/1bbef358249b4fb6821a233a2fcb934c0efef04e/regular/about.html#L29 Though this could be further changed to reflect the digital nature of future "posters".
- [x]  Style: On the about page the below paragraph has inconsistent capitalisation, newer positions [Are in Title Case](https://tvtropes.org/pmwiki/pmwiki.php/Main/SelfDemonstratingArticle), whereas older positions are all lower case. https://github.com/HackSoc/hacksoc.org/blob/1bbef358249b4fb6821a233a2fcb934c0efef04e/regular/about.html#L56-L59
- [x] Grammar: On the about page below paragraph should have a comma before the "such as" as it is a nonrestrictive use of "such as". https://github.com/HackSoc/hacksoc.org/blob/1bbef358249b4fb6821a233a2fcb934c0efef04e/regular/about.html#L31-L33
- [x] Grammar: On the IRC page the below line should have a capital "a" after the question mark. https://github.com/HackSoc/hacksoc.org/blob/1bbef358249b4fb6821a233a2fcb934c0efef04e/regular/irc.html#L6
- [x] Nitpick: Pointless extra newline which ruins the pattern. See below blank newline (because I have [gone mad with the referencing power](https://tvtropes.org/pmwiki/pmwiki.php/Main/DrunkWithPower)). https://github.com/HackSoc/hacksoc.org/blob/1bbef358249b4fb6821a233a2fcb934c0efef04e/templates/index.handlebars#L23
- [x] Grammar: On the runciman server page there should be a full stop at the end of the bellow line. https://github.com/HackSoc/hacksoc.org/blob/1bbef358249b4fb6821a233a2fcb934c0efef04e/servers/runciman.md#L28
- [x] Grammar: On the IRC page there should be a full stop at the end of the below sentence. https://github.com/HackSoc/hacksoc.org/blob/1bbef358249b4fb6821a233a2fcb934c0efef04e/regular/irc.html#L10-L11
- [x] Style: We may consider changing this section so that [Computer Science](https://tvtropes.org/pmwiki/pmwiki.php/Main/SelfDemonstratingArticle) is in title case as [Computer Science](https://tvtropes.org/pmwiki/pmwiki.php/Main/OverusedRunningGag) is regularly in title case elsewhere on the about page.
https://github.com/HackSoc/hacksoc.org/blob/1bbef358249b4fb6821a233a2fcb934c0efef04e/regular/about.html#L61-L88
- [x] Style: Slack should be written as a proper noun (with a capital first letter) on the below lines, possibly covered by #64 however I thought it important to list the actual lines.
 https://github.com/HackSoc/hacksoc.org/blob/1bbef358249b4fb6821a233a2fcb934c0efef04e/regular/irc.html#L16 https://github.com/HackSoc/hacksoc.org/blob/1bbef358249b4fb6821a233a2fcb934c0efef04e/regular/irc.html#L10
- [x] Typo: Use of "cannonicalize" in the below comment should be "canonicalise". https://github.com/HackSoc/hacksoc.org/blob/1bbef358249b4fb6821a233a2fcb934c0efef04e/main.js#L11 We're going [Up To Eleven](https://tvtropes.org/pmwiki/pmwiki.php/Main/UpToEleven) in nitpicking (on line 11, no less) on this one.

As a small note: I hope the below lines don't render as strike throughs in the final version as they do on github (I'm currently unable to check due to being in Wales). I assume they don't and it's just me worrying. https://github.com/HackSoc/hacksoc.org/blob/1bbef358249b4fb6821a233a2fcb934c0efef04e/servers/runciman.md#L32

(I also offer this issue as an example of [this phenomenon](https://tvtropes.org/pmwiki/pmwiki.php/JustForFun/TVTropesWillRuinYourVocabulary).)

**Comment by LukeMoll** [comment]
Fixed in [39a999d](https://github.com/HackSoc/hacksoc.org/commit/39a999d9a4b4d70a9dc4d211e529550ba9b5743f):

 - Paragraph style is to not use hard wraps (except on news content, because I can't be bothered to un-hard-wrap that and it kinda makes sense there). I've added a note in the README about it
 - Computer Science and committee positions are now all Title Case. 
 - Slack is now a proper noun, except in the navbar, where it's all lowercase (consistently)

If you're happy all of these are met, feel free to close the issue. Otherwise I'll do it in a week
