### ISSUE TITLE
Calendar: current day is not highlighted when in the previous/next month

### ISSUE THREAD

**Issue by sersorrel** [HackSoc/hacksoc.org#93]
Previously:

![image](https://user-images.githubusercontent.com/9433472/69916101-79b2ff80-144e-11ea-8ebe-fd5d7c4ea4e1.png)

Now:

![image](https://user-images.githubusercontent.com/9433472/69916098-71f35b00-144e-11ea-854f-8a866ebfb1ee.png)

**Comment by AaronC81** [comment]
Sorry It's taken me a while to fix this, the issue was raised last decade

![Open eye laughing emoji](https://stuff.aaronc.cc/uploads/yoj.png)

It _should_ be fixed now, but I'll wait until the date is actually one near the end or start of a month to double-check.

**Comment by AaronC81** [comment]
Checked this by changing the time of my computer and it seems to be fixed.
